### ISSUE TITLE
issues in gitlab

### ISSUE THREAD

**Issue by lejeanf** [TomDuchene/unity-git-locks#4]
hi,

I have a problem with unity-git-lock

- I have LFS enabled
- I did input my user name from gitlab
- I ran "git config lfs.setlockablereadonly false" in my console

what's happening:
- I can lock the file but it appears in "Other locks" category
- I can only unlock when using force unlock
- other user cannot push when any file is locked

Did I miss something?

**Comment by TomDuchene** [comment]
Hi!
Given your symptoms I would start by trying to make locks works via command line first.

The main commands are `git lfs locks` to see the list of existing locks, `git lfs lock path/to/file` and `git lfs unlock path/to/file`.

Since you're mentioning Gitlab it's possible that things work a bit differently there, especially the username that identifies who took the lock, which you'll see easily with the "locks" command and might solve your first problem.
Once you get everything working in command line we can see if there are remaining problems to be solved in the tool itself!

(It's fun to see you worked for Théoriz one year after I left, you probably read some of my code before ! It's a small world 😄)

**Comment by lejeanf** [comment]
wierdly enough I removed the @myMailProvider.test from my user in your editor window and it started to work
even though in gitbash I need to input the whole email as username. confusing but well, now it works!
